name: scheduled health check

# on: 
#   schedule:
#     - cron: '0 11 * * *'

on:
  push:
    branches:
      - master

jobs: 
  health-check:
    runs-on: ubuntu-18.04
    steps: 
      - name: service url health sheck
        uses: Jtalk/url-health-check-action@v2
        with: 
          url: https://quiet-falls-26132.herokuapp.com/health|https://quiet-falls-26132.herokuapp.com/version
          follow-redirect: false
          max-attempts: 2
          retry-delay: 50s